# Site settings
title: Tao's page
baseurl: "/"
url: "https://taovv.github.io"
google_analytics: # Tracking ID, e.g. "UA-000000-01"

author:
  name: Tao Wang
  desc: Hello nice to meet you
  email: taovvang@gmail.com
  phone: (+86)185-898-31214
  location: Shenzhen
  selfie: assets/img/pic.jpg
  ico: assets/tao.ico
  cv_ch:  assets/taowang_CV_CH.pdf
  cv: assets/TaoWang_CV_EN.pdf

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: taovv
  google_plus:
  instagram:
  keybase:
  linkedin:
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter:
  vimeo:
  wordpress:
  youtube:
  yuque: taoo
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
